export interface RolePreset {
  name: string;
  roleKey: string;
  description: string;
  icon: string;
  modules: string[];
}

export const ALL_REPORT_PERMISSION_IDS = [
  '/Reports/Reports-Dashboard',
  // Sales Reports (8)
  'report:category-wise-sales',
  'report:product-sales-history',
  'report:sale-inv-detail',
  'report:commercial-sale-ledger',
  'report:sales-query-center',
  'report:sales-return-ledger',
  'report:customer-sales-breakdown',
  'report:customer-loyalty-ledger',
  '/Reports/Sales-Report',
  // Purchases & Payables (8)
  'report:purchase-ledger',
  'report:category-purchases',
  'report:product-purchase-history',
  'report:purchase-invoice-detail',
  'report:purchase-query-center',
  'report:vendor-return-ledger',
  'report:vendor-balance-detail-pur',
  'report:vendor-outstanding-report-pur',
  '/Reports/Purchase-Report',
  // Inventory & Stock (7)
  'report:stock-activity-ledger',
  'report:current-stock-balance',
  'report:as-of-date-stock-status',
  'report:inter-warehouse-transfers',
  'report:category-wise-stock',
  'report:warehouse-location-report',
  'report:holding-stock-report',
  '/Reports/Stock-Report',
  '/Reports/Holding-Report',
  // Accounts & Financials (9)
  'report:customer-balance-detail',
  'report:vendor-balance-detail',
  'report:customer-ledger',
  'report:daybook-activity-report',
  'report:customer-aging-report',
  'report:voucher-audit-register',
  'report:trial-balance-statement',
  'report:vendor-outstanding-report',
  'report:expense-ledger',
  '/Reports/Account-Report',
  // Business Overview (2)
  'report:balance-sheet-stat',
  'report:executive-summary-report',
  '/Reports/Balance-Sheet',
];

export const ROLE_PRESETS: Record<string, RolePreset> = {
  'Super Admin': {
    name: 'Super Admin / Owner',
    roleKey: 'Super Admin',
    description: 'Full unrestricted system access to all business modules, financial data, and controls.',
    icon: '👑',
    modules: [
      'dashboards',
      'dashboard',
      '/Dashboard/Salesman',
      '/Dashboard/Warehouse',
      '/Administration/Categories/List',
      '/Administration/Surface-Finish',
      '/Administration/UOM/List',
      '/Administration/Brands',
      '/Administration/Products/List',
      '/Administration/Products/Bulk-Upload',
      '/Administration/Locations/List',
      '/Administration/Transportation/List',
      '/Administration/StockTransfer/List',
      '/company',
      '/Registration/Chart-of-Account/List',
      '/Registration/Vouchers/List',
      '/Registration/Bank-Account/BankAccountList',
      '/Inventory/OpeningStock/List',
      '/Sales/Invoice/List',
      '/sales/invoice/list',
      '/Sales/InvoiceReceipt/List',
      '/Registration/InvoiceReceipt/List',
      '/Sales/Sales-Return/List',
      '/Sales-Return/Debit-Notes/List',
      '/Sales/Sales-Return-Receipt/List',
      '/sales/sales-return-receipt/list',
      '/Sales/Customers/List',
      '/Customers/list',
      '/Sales/Salesman/List',
      '/Salesman/list',
      '/Sales/Delivery-Challan/List',
      '/Delivery-Challan/List',
      '/Sales/Shop-Dispatch/List',
      '/Purchase/Purchases/List',
      '/Purchase/Inward-Challan/List',
      '/Purchase/Shop-Receiving',
      '/Purchase/Purchase-Receipt/List',
      '/Purchase/Purchase-Return/List',
      '/Purchase/Purchase-Return-Receipt/List',
      '/Purchase/Vendor/List',
      '/Warehouse/Return-Challan',
      '/Warehouse/Shop-Return',
      'reports_hub',
      'reports_sales',
      'reports_purchases',
      'reports_inventory',
      'reports_accounts',
      'reports_business',
      ...ALL_REPORT_PERMISSION_IDS,
    ],
  },
  'Salesman': {
    name: 'Salesman',
    roleKey: 'Salesman',
    description: 'Restricted access: Sale Invoice, Invoice Receipts, Sales Returns, Return Receipt, Debit Notes, and Sales Reports.',
    icon: '🛒',
    modules: [
      'dashboards',
      '/Dashboard/Salesman',
      'sales',
      '/Sales/Invoice/List',
      '/sales/invoice/list',
      '/Sales/InvoiceReceipt/List',
      '/Registration/InvoiceReceipt/List',
      '/Sales/Sales-Return/List',
      '/sales/sales-return/list',
      '/Sales-Return/Debit-Notes/List',
      '/Sales/Sales-Return-Receipt/List',
      '/sales/sales-return-receipt/list',
      '/Sales/Customers/List',
      '/Customers/list',
      'reports_hub',
      '/Reports/Reports-Dashboard',
      'reports_sales',
      '/Reports/Sales-Report',
      'report:category-wise-sales',
      'report:product-sales-history',
      'report:sale-inv-detail',
      'report:commercial-sale-ledger',
      'report:sales-query-center',
      'report:sales-return-ledger',
      'report:customer-sales-breakdown',
      'report:customer-loyalty-ledger',
    ],
  },
  'Warehouse Manager': {
    name: 'Warehouse / Inventory Manager',
    roleKey: 'Warehouse Manager',
    description: 'Manages products, stock transfers, locations, opening stock, delivery challans, and stock reports.',
    icon: '📦',
    modules: [
      'dashboards',
      '/Dashboard/Warehouse',
      '/Administration/Categories/List',
      '/Administration/Surface-Finish',
      '/Administration/UOM/List',
      '/Administration/Brands',
      '/Administration/Products/List',
      '/Administration/Products/Bulk-Upload',
      '/Administration/Locations/List',
      '/Administration/Transportation/List',
      '/Administration/StockTransfer/List',
      '/Inventory/OpeningStock/List',
      '/Sales/Delivery-Challan/List',
      '/Delivery-Challan/List',
      '/Sales/Shop-Dispatch/List',
      '/Purchase/Inward-Challan/List',
      '/Purchase/Shop-Receiving',
      '/Warehouse/Return-Challan',
      '/Warehouse/Shop-Return',
      'reports_hub',
      '/Reports/Reports-Dashboard',
      'reports_inventory',
      '/Reports/Stock-Report',
      '/Reports/Holding-Report',
      'report:stock-activity-ledger',
      'report:current-stock-balance',
      'report:as-of-date-stock-status',
      'report:inter-warehouse-transfers',
      'report:category-wise-stock',
      'report:warehouse-location-report',
      'report:holding-stock-report',
    ],
  },
  'Accountant': {
    name: 'Accountant / Financial Officer',
    roleKey: 'Accountant',
    description: 'Manages chart of accounts, financial vouchers, bank accounts, receipts, balance sheet, and financial reports.',
    icon: '📊',
    modules: [
      'dashboard',
      '/Registration/Chart-of-Account/List',
      '/Registration/Vouchers/List',
      '/Registration/Bank-Account/BankAccountList',
      '/Sales/InvoiceReceipt/List',
      '/Registration/InvoiceReceipt/List',
      '/Sales/Sales-Return-Receipt/List',
      '/sales/sales-return-receipt/list',
      '/Purchase/Purchase-Receipt/List',
      '/Purchase/Purchase-Return-Receipt/List',
      'reports_hub',
      '/Reports/Reports-Dashboard',
      'reports_accounts',
      '/Reports/Account-Report',
      'report:customer-balance-detail',
      'report:vendor-balance-detail',
      'report:customer-ledger',
      'report:daybook-activity-report',
      'report:customer-aging-report',
      'report:voucher-audit-register',
      'report:trial-balance-statement',
      'report:vendor-outstanding-report',
      'report:expense-ledger',
      'reports_business',
      '/Reports/Balance-Sheet',
      'report:balance-sheet-stat',
      'report:executive-summary-report',
    ],
  },
};

export const getModulesForRole = (role: string): string[] => {
  const preset = ROLE_PRESETS[role];
  if (preset) return preset.modules;
  if (role && role.toLowerCase().includes('admin')) {
    return ROLE_PRESETS['Super Admin'].modules;
  }
  return ROLE_PRESETS['Super Admin'].modules;
};
